### ISSUE TITLE
有个 bug，望修改

### ISSUE THREAD

**Issue by echoQMC** [easy-swoole/fast-cache#12]
1.2.1 版本

![image](https://user-images.githubusercontent.com/13032733/63082403-bed32480-bf78-11e9-970b-a16b471db22b.png)

**Comment by echoQMC** [comment]
这个 get set 反了
![image](https://user-images.githubusercontent.com/13032733/63082557-18d3ea00-bf79-11e9-9e53-94c147f5fee6.png)

**Comment by kiss291323003** [comment]
已经解决，感谢反馈，晚上或者明天稍后发版本
