### ISSUE TITLE
Cache::getInstance()->hset()后，自动减少数据，自动更改数据

### ISSUE THREAD

**Issue by alanstars** [easy-swoole/fast-cache#22]
$register->set($register::onOpen, function ($server, $request) {
            $dateTime = date('Y-m-d H:i:s');
            // ws://127.0.0.1:9501/?client=collect
            if(isset($request->get["client"]) && $request->get["client"] == "collect"){
                // 设备验证状态 1 空闲 2 工作
                Cache::getInstance()->hset('collectFds', $request->fd, 1);
                $msgData = [
                    'code' => 200,
                    'msg' => 'connect success',
                    'data' => [],
                ];
                $str = "{$dateTime} 建立客户端 onOpen -- gather设备认证客户端";
            }else{
                // 状态 1 空闲 2 工作
                Cache::getInstance()->hset('fd', $request->fd, 1);
                $msgData = [
                    'code' => 200,
                    'msg' => '成功',
                    'data' => [
                        'type' => 1, //1 图鉴信息  2 极验信息
                        'username' => 'administrator8',
                        'password' => 'doittome10',
                    ],
                ];
                $str = "{$dateTime} 建立客户端 onOpen -- 登录签到客户端";
            }
            echo "{$str} client-{$request->fd}  is open \n";
            $server->push($request->fd, json_encode($msgData));
        });

protected function run($arg)
    {
        while (true) {
            $dateTime = date('Y-m-d H:i:s');
            //处理fd以及状态
            $arr = [];
            $fdList = Cache::getInstance()->hGetAll('fd');

            print_r("fdList:");
            print_r($fdList);
            sleep(5);
    }
}

使用webSocket的，用户onOpen时Cache::getInstance()->hset('fd', $request->fd, 1);数据存到哈希中，key为fd，field为fd，value为1；
当我取哈希中的数据时：Cache::getInstance()->hGetAll('fd');
前三次数据正常，第四次开始会减少数据，而且会串改其中value值，打印结果如下：

`
(
    [0] => 1
    [1] => 1
    [2] => 2
    [3] => 1
)

(
    [0] => 1
    [1] => 1
    [2] => 2
    [3] => 1
)

(
    [0] => 1
    [1] => 1
    [2] => 2
    [3] => 1
)

(
    [0] => 1
    [1] => 2
)
`

**Comment by lovejc1314** [comment]
您好，请问您用的 easyswoole 是什么版本？fast-cache 是怎么配置的呢？我这边使用 easyswoole 3.4.4 测试是一切正常的，不会出现您说的这种问题。

**Comment by lovejc1314** [comment]
注册回调代码如下：
<?php


namespace EasySwoole\EasySwoole;


use App\Processes\CustomProcess;
use EasySwoole\EasySwoole\AbstractInterface\Event;
use EasySwoole\EasySwoole\Swoole\EventRegister;
use EasySwoole\FastCache\Cache;

class EasySwooleEvent implements Event
{
    public static function initialize()
    {
        date_default_timezone_set('Asia/Shanghai');
    }

    public static function mainServerCreate(EventRegister $register)
    {
        $register->set($register::onOpen, function ($server, $request) {
            $dateTime = date('Y-m-d H:i:s');
            // ws://127.0.0.1:9501/?client=collect
            if (isset($request->get["client"]) && $request->get["client"] == "collect") {
                // 设备验证状态 1 空闲 2 工作
                Cache::getInstance()->hset('collectFds', $request->fd, '我是 client' . time());
                $msgData = [
                    'code' => 200,
                    'msg' => 'connect success',
                    'data' => [],
                ];
                $str = "{$dateTime} 建立客户端 onOpen -- gather设备认证客户端";
            } else {
                // 状态 1 空闲 2 工作
                Cache::getInstance()->hset('fd', $request->fd, '我是fd-' . time());
                $msgData = [
                    'code' => 200,
                    'msg' => '成功',
                    'data' => [
                        'type' => 1, //1 图鉴信息 2 极验信息
                        'username' => 'administrator8',
                        'password' => 'doittome10',
                    ],
                ];
                $str = "{$dateTime} 建立客户端 onOpen -- 登录签到客户端";
            }
            echo "{$str} client-{$request->fd} is open \n";
            $server->push($request->fd, json_encode($msgData));
        });

        $register->set($register::onMessage, function (\Swoole\WebSocket\Server $server, \Swoole\WebSocket\Frame $frame) {
            echo "Message: {$frame->data}\n";
            $server->push($frame->fd, "server: {$frame->data}");
        });

        $register->set($register::onClose, function ($ws, $fd) {
            echo "client-{$fd} is closed\n";
        });

        // 在最新的2.x中，改为config配置文件配置
        $config = new \EasySwoole\FastCache\Config();
        $config->setTempDir(EASYSWOOLE_TEMP_DIR);
        Cache::getInstance($config)->attachToServer(ServerManager::getInstance()->getSwooleServer());

        $proConfig = new \EasySwoole\Component\Process\Config([
            'processName' => 'CustomProcess', // 设置 自定义进程名称
            'processGroup' => 'Custom', // 设置 自定义进程组名称
            'enableCoroutine' => true, // 设置 自定义进程自动开启协程
        ]);
        // 注册 fast-cache
        \EasySwoole\Component\Process\Manager::getInstance()->addProcess(new CustomProcess($proConfig));
    }
}

自定义进程代码如下：
<?php

namespace App\Processes;

use EasySwoole\Component\Process\AbstractProcess;
use EasySwoole\FastCache\Cache;

class CustomProcess extends AbstractProcess
{
    protected function run($arg)
    {
        while (true) {

            $dateTime = date('Y-m-d H:i:s');
            // 处理fd以及状态
            $arr = [];

            $fdList = Cache::getInstance()->hGetAll('fd');

            echo str_repeat(PHP_EOL, 2);
            echo '======';
            echo $dateTime;
            echo PHP_EOL . '我是自定义进程' . PHP_EOL;
            var_dump("fdList:");
            var_dump($fdList);
            echo '======';
            echo str_repeat(PHP_EOL, 2);
            
            sleep(3);
            // 这里请务必使用 协程方式 sleep(3);
            // \Swoole\Coroutine::sleep(3);
        }
    }
}

dev.php 配置 MAIN_SERVER.SERVER_TYPE 为 EASYSWOOLE_WEB_SOCKET_SERVER，即 ws服务。

**Comment by alanstars** [comment]
> 您好，请问您用的 easyswoole 是什么版本？fast-cache 是怎么配置的呢？我这边使用 easyswoole 3.4.4 测试是一切正常的，不会出现您说的这种问题。

ES版本3.4.4，Fast-cache版本为2.0.0

**Comment by Player626** [comment]
您确定抽离出来了最小复现代码来测试?

**Comment by lovejc1314** [comment]
请提供全部的最小复现代码，和具体环境配置，例如： php版本、swoole 版本这些

**Comment by alanstars** [comment]
我安装一个新版本抽离出来试试

**Comment by Player626** [comment]
请用如下代码测试：
```
public static function mainServerCreate(EventRegister $register)
    {
        Cache::getInstance()->attachToServer(ServerManager::getInstance()->getSwooleServer());
        $register->set($register::onOpen, function ($server, $request) {

            $dateTime = date('Y-m-d H:i:s');
// ws://127.0.0.1:9501/?client=collect
            if (isset($request->get["client"]) && $request->get["client"] == "collect") {
// 设备验证状态 1 空闲 2 工作
                Cache::getInstance()->hset('collectFds', $request->fd, 1);
                $msgData = [
                    'code' => 200,
                    'msg' => 'connect success',
                    'data' => [],
                ];
                $str = "{$dateTime} 建立客户端 onOpen -- gather设备认证客户端";
            } else {
// 状态 1 空闲 2 工作
                Cache::getInstance()->hset('fd', $request->fd, 1);

                $msgData = [
                    'code' => 200,
                    'msg' => '成功',
                    'data' => [
                        'type' => 1, //1 图鉴信息 2 极验信息
                        'username' => 'administrator8',
                        'password' => 'doittome10',
                    ],
                ];
                $str = "{$dateTime} 建立客户端 onOpen -- 登录签到客户端";
            }
            echo "{$str} client-{$request->fd} is open \n";
            $server->push($request->fd, json_encode($msgData));
        });

        $register->set('message', function () {

        });

        Timer::getInstance()->loop(1000, function () {
            var_dump(Cache::getInstance()->hGetAll('fd'));
        });
    }
```

**Comment by alanstars** [comment]
我单独装了一个新的环境，用这个最小的测试单元去测试没问题，我再看下自己的代码
