### ISSUE TITLE
array_key_exists(): Using array_key_exists() on objects is deprecated

### ISSUE THREAD

**Issue by 523013183** [easy-swoole/fast-cache#23]
使用 Cache::getInstance()->expire(‘key’, 30); //重置过期时间 

会出现array_key_exists(): Using array_key_exists() on objects is deprecated. Use isset() or property_exists() instead at file:/var/www/aaa/vendor/easyswoole/fast-cache/src/CacheProcess.php line:376   错误

php环境 7.4 
设置了10个 fast-cache ProcessNum
Cache::getInstance()->setTempDir(EASYSWOOLE_TEMP_DIR)->setProcessNum(10)

**Comment by Player626** [comment]
`fast-cache`版本多少？

**Comment by Player626** [comment]
这个错误是`php7.4`废弃的一个特性.

**Comment by Player626** [comment]
如果你没有使用到`fast-cache 1.x`版本的数据落地功能.直接更新到`fast-cache 2.x`版本即可.

**Comment by 523013183** [comment]
> `fast-cache`版本多少？

1.3

**Comment by 523013183** [comment]
> 如果你没有使用到`fast-cache 1.x`版本的数据落地功能.直接更新到`fast-cache 2.x`版本即可.
好的，我试下。

**Comment by Player626** [comment]
https://github.com/easy-swoole/fast-cache/releases/tag/1.3.2

**Comment by Player626** [comment]
采用`1.3.2`或者`2.0`都可以.
